-- Insert All Categories into categories_list table
INSERT INTO categories_list (category_name) VALUES ('DB Saga');
INSERT INTO categories_list (category_name) VALUES ('Saiyan Saga');
INSERT INTO categories_list (category_name) VALUES ('Planet Namek Saga');
INSERT INTO categories_list (category_name) VALUES ('Androids/Cell Saga');
INSERT INTO categories_list (category_name) VALUES ('Majin Buu Saga');
INSERT INTO categories_list (category_name) VALUES ('Future Saga');
INSERT INTO categories_list (category_name) VALUES ('Universe Survival Saga');
INSERT INTO categories_list (category_name) VALUES ('Shadow Dragon Saga');
INSERT INTO categories_list (category_name) VALUES ('Pure Saiyans');
INSERT INTO categories_list (category_name) VALUES ('Hybrid Saiyans');
INSERT INTO categories_list (category_name) VALUES ('Earthlings');
INSERT INTO categories_list (category_name) VALUES ('Namekians');
INSERT INTO categories_list (category_name) VALUES ('Androids');
INSERT INTO categories_list (category_name) VALUES ('Artificial Life Forms');
INSERT INTO categories_list (category_name) VALUES ('Goku''s Family');
INSERT INTO categories_list (category_name) VALUES ('Vegeta''s Family');
INSERT INTO categories_list (category_name) VALUES ('Wicked Bloodline');
INSERT INTO categories_list (category_name) VALUES ('Youth');
INSERT INTO categories_list (category_name) VALUES ('Peppy Gals');
INSERT INTO categories_list (category_name) VALUES ('Super Saiyans');
INSERT INTO categories_list (category_name) VALUES ('Super Saiyan 2');
INSERT INTO categories_list (category_name) VALUES ('Super Saiyan 3');
INSERT INTO categories_list (category_name) VALUES ('Power Beyond Super Saiyan');
INSERT INTO categories_list (category_name) VALUES ('Fusion');
INSERT INTO categories_list (category_name) VALUES ('Potara');
INSERT INTO categories_list (category_name) VALUES ('Fused Fighters');
INSERT INTO categories_list (category_name) VALUES ('Giant Form');
INSERT INTO categories_list (category_name) VALUES ('Transformation Boost');
INSERT INTO categories_list (category_name) VALUES ('Power Absorption');
INSERT INTO categories_list (category_name) VALUES ('Kamehameha');
INSERT INTO categories_list (category_name) VALUES ('Realm of Gods');
INSERT INTO categories_list (category_name) VALUES ('Full Power');
INSERT INTO categories_list (category_name) VALUES ('Giant Ape Power');
INSERT INTO categories_list (category_name) VALUES ('Majin Power');
INSERT INTO categories_list (category_name) VALUES ('Uncontrollable Power');
INSERT INTO categories_list (category_name) VALUES ('Powerful Comeback');
INSERT INTO categories_list (category_name) VALUES ('Power of Wishes');
INSERT INTO categories_list (category_name) VALUES ('Demonic Power');
INSERT INTO categories_list (category_name) VALUES ('Miraculous Awakening');
INSERT INTO categories_list (category_name) VALUES ('Corroded Body and Mind');
INSERT INTO categories_list (category_name) VALUES ('Rapid Growth');
INSERT INTO categories_list (category_name) VALUES ('Mastered Evolution');
INSERT INTO categories_list (category_name) VALUES ('Time Limit');
INSERT INTO categories_list (category_name) VALUES ('Final Trump Card');
INSERT INTO categories_list (category_name) VALUES ('Worthy Rivals');
INSERT INTO categories_list (category_name) VALUES ('Sworn Enemies');
INSERT INTO categories_list (category_name) VALUES ('Joined Forces');
INSERT INTO categories_list (category_name) VALUES ('Bond of Parent and Child');
INSERT INTO categories_list (category_name) VALUES ('Siblings'' Bond');
INSERT INTO categories_list (category_name) VALUES ('Bond of Friendship');
INSERT INTO categories_list (category_name) VALUES ('Bond of Master and Disciple');
INSERT INTO categories_list (category_name) VALUES ('Ginyu Force');
INSERT INTO categories_list (category_name) VALUES ('Team Bardock');
INSERT INTO categories_list (category_name) VALUES ('Universe 6');
INSERT INTO categories_list (category_name) VALUES ('Representatives of Universe 7');
INSERT INTO categories_list (category_name) VALUES ('Universe 11');
INSERT INTO categories_list (category_name) VALUES ('GT Heroes');
INSERT INTO categories_list (category_name) VALUES ('GT Bosses');
INSERT INTO categories_list (category_name) VALUES ('Super Heroes');
INSERT INTO categories_list (category_name) VALUES ('Super Bosses');
INSERT INTO categories_list (category_name) VALUES ('Movie Heroes');
INSERT INTO categories_list (category_name) VALUES ('Movie Bosses');
INSERT INTO categories_list (category_name) VALUES ('Turtle School');
INSERT INTO categories_list (category_name) VALUES ('World Tournament');
INSERT INTO categories_list (category_name) VALUES ('Tournament Participants');
INSERT INTO categories_list (category_name) VALUES ('Earth-Bred Fighters');
INSERT INTO categories_list (category_name) VALUES ('Low-Class Warrior');
INSERT INTO categories_list (category_name) VALUES ('Gifted Warriors');
INSERT INTO categories_list (category_name) VALUES ('Otherworld Warriors');
INSERT INTO categories_list (category_name) VALUES ('Resurrected Warriors');
INSERT INTO categories_list (category_name) VALUES ('Space-Traveling Warriors');
INSERT INTO categories_list (category_name) VALUES ('Time Travelers');
INSERT INTO categories_list (category_name) VALUES ('Dragon Ball Seekers');
INSERT INTO categories_list (category_name) VALUES ('Successors');
INSERT INTO categories_list (category_name) VALUES ('Storied Figures');
INSERT INTO categories_list (category_name) VALUES ('Legendary Existence');
INSERT INTO categories_list (category_name) VALUES ('Saviors');
INSERT INTO categories_list (category_name) VALUES ('Defenders of Justice');
INSERT INTO categories_list (category_name) VALUES ('Earth-Protecting Heroes');
INSERT INTO categories_list (category_name) VALUES ('Revenge');
INSERT INTO categories_list (category_name) VALUES ('Target: Goku');
INSERT INTO categories_list (category_name) VALUES ('Terrifying Conquerors');
INSERT INTO categories_list (category_name) VALUES ('Inhuman Deeds');
INSERT INTO categories_list (category_name) VALUES ('Planetary Destruction');
INSERT INTO categories_list (category_name) VALUES ('Exploding Rage');
INSERT INTO categories_list (category_name) VALUES ('Connected Hope');
INSERT INTO categories_list (category_name) VALUES ('Entrusted Will');
INSERT INTO categories_list (category_name) VALUES ('All-Out Struggle');
INSERT INTO categories_list (category_name) VALUES ('Battle of Wits');
INSERT INTO categories_list (category_name) VALUES ('Accelerated Battle');
INSERT INTO categories_list (category_name) VALUES ('Battle of Fate');
INSERT INTO categories_list (category_name) VALUES ('Heavenly Events');
INSERT INTO categories_list (category_name) VALUES ('Special Pose');
INSERT INTO categories_list (category_name) VALUES ('Worldwide Chaos');
INSERT INTO categories_list (category_name) VALUES ('Crossover');
INSERT INTO categories_list (category_name) VALUES ('Dragon Ball Heroes');
