-- Insert All Links into links_list table
INSERT INTO links_list (link_name) VALUES ('All in the Family');
INSERT INTO links_list (link_name) VALUES ('Android Assault');
INSERT INTO links_list (link_name) VALUES ('Attack of the Clones');
INSERT INTO links_list (link_name) VALUES ('Auto Regeneration');
INSERT INTO links_list (link_name) VALUES ('Battlefield Diva');
INSERT INTO links_list (link_name) VALUES ('Berserker');
INSERT INTO links_list (link_name) VALUES ('Big Bad Bosses');
INSERT INTO links_list (link_name) VALUES ('Blazing Battle');
INSERT INTO links_list (link_name) VALUES ('Bombardment');
INSERT INTO links_list (link_name) VALUES ('Brainiacs');
INSERT INTO links_list (link_name) VALUES ('Brutal Beatdown');
INSERT INTO links_list (link_name) VALUES ('Budding Warrior');
INSERT INTO links_list (link_name) VALUES ('Champion''s Strength');
INSERT INTO links_list (link_name) VALUES ('Cold Judgment');
INSERT INTO links_list (link_name) VALUES ('Connoisseur');
INSERT INTO links_list (link_name) VALUES ('Cooler''s Armored Squad');
INSERT INTO links_list (link_name) VALUES ('Cooler''s Underling');
INSERT INTO links_list (link_name) VALUES ('Courage');
INSERT INTO links_list (link_name) VALUES ('Coward');
INSERT INTO links_list (link_name) VALUES ('Crane School');
INSERT INTO links_list (link_name) VALUES ('Deficit Boost');
INSERT INTO links_list (link_name) VALUES ('Demonic Power');
INSERT INTO links_list (link_name) VALUES ('Demonic Ways');
INSERT INTO links_list (link_name) VALUES ('Destroyer of the Universe');
INSERT INTO links_list (link_name) VALUES ('Dismal Future');
INSERT INTO links_list (link_name) VALUES ('Dodon Ray');
INSERT INTO links_list (link_name) VALUES ('Energy Absorption');
INSERT INTO links_list (link_name) VALUES ('Evil Autocrats');
INSERT INTO links_list (link_name) VALUES ('Experienced Fighters');
INSERT INTO links_list (link_name) VALUES ('Family Ties');
INSERT INTO links_list (link_name) VALUES ('Fear and Faith');
INSERT INTO links_list (link_name) VALUES ('Fierce Battle');
INSERT INTO links_list (link_name) VALUES ('Flee');
INSERT INTO links_list (link_name) VALUES ('Formidable Enemy');
INSERT INTO links_list (link_name) VALUES ('Fortuneteller Baba''s Fighter');
INSERT INTO links_list (link_name) VALUES ('Frieza''s Army');
INSERT INTO links_list (link_name) VALUES ('Frieza''s Minion');
INSERT INTO links_list (link_name) VALUES ('Fused Fighter');
INSERT INTO links_list (link_name) VALUES ('Fusion');
INSERT INTO links_list (link_name) VALUES ('Fusion Failure');
INSERT INTO links_list (link_name) VALUES ('GT');
INSERT INTO links_list (link_name) VALUES ('Galactic Visitor');
INSERT INTO links_list (link_name) VALUES ('Galactic Warriors');
INSERT INTO links_list (link_name) VALUES ('Gaze of Respect');
INSERT INTO links_list (link_name) VALUES ('Gentleman');
INSERT INTO links_list (link_name) VALUES ('Godly Power');
INSERT INTO links_list (link_name) VALUES ('Golden Warrior');
INSERT INTO links_list (link_name) VALUES ('Golden Z-Fighter');
INSERT INTO links_list (link_name) VALUES ('Guidance of the Dragon Balls');
INSERT INTO links_list (link_name) VALUES ('Hardened Grudge');
INSERT INTO links_list (link_name) VALUES ('Hatred of Saiyans');
INSERT INTO links_list (link_name) VALUES ('Hero');
INSERT INTO links_list (link_name) VALUES ('Hero of Justice');
INSERT INTO links_list (link_name) VALUES ('High Compatibility');
INSERT INTO links_list (link_name) VALUES ('Infighter');
INSERT INTO links_list (link_name) VALUES ('Infinite Energy');
INSERT INTO links_list (link_name) VALUES ('Infinite Regeneration');
INSERT INTO links_list (link_name) VALUES ('Kamehameha');
INSERT INTO links_list (link_name) VALUES ('Legendary Power');
INSERT INTO links_list (link_name) VALUES ('Limit-Breaking Form');
INSERT INTO links_list (link_name) VALUES ('Loyalty');
INSERT INTO links_list (link_name) VALUES ('Majin');
INSERT INTO links_list (link_name) VALUES ('Majin Resurrection Plan');
INSERT INTO links_list (link_name) VALUES ('Master of Magic');
INSERT INTO links_list (link_name) VALUES ('Mechanical Menaces');
INSERT INTO links_list (link_name) VALUES ('Messenger from the Future');
INSERT INTO links_list (link_name) VALUES ('Metamorphosis');
INSERT INTO links_list (link_name) VALUES ('Money Money Money');
INSERT INTO links_list (link_name) VALUES ('More Than Meets the Eye');
INSERT INTO links_list (link_name) VALUES ('Namekians');
INSERT INTO links_list (link_name) VALUES ('New');
INSERT INTO links_list (link_name) VALUES ('New Frieza Army');
INSERT INTO links_list (link_name) VALUES ('Nightmare');
INSERT INTO links_list (link_name) VALUES ('Organic Upgrade');
INSERT INTO links_list (link_name) VALUES ('Otherworld Warriors');
INSERT INTO links_list (link_name) VALUES ('Over 9000');
INSERT INTO links_list (link_name) VALUES ('Over in a Flash');
INSERT INTO links_list (link_name) VALUES ('Patrol');
INSERT INTO links_list (link_name) VALUES ('Penguin Village Adventure');
INSERT INTO links_list (link_name) VALUES ('Power Bestowed by God');
INSERT INTO links_list (link_name) VALUES ('Prepared for Battle');
INSERT INTO links_list (link_name) VALUES ('Prodigies');
INSERT INTO links_list (link_name) VALUES ('RR Army');
INSERT INTO links_list (link_name) VALUES ('Respect');
INSERT INTO links_list (link_name) VALUES ('Resurrection ''F''');
INSERT INTO links_list (link_name) VALUES ('Revival');
INSERT INTO links_list (link_name) VALUES ('Royal Lineage');
INSERT INTO links_list (link_name) VALUES ('Saiyan Pride');
INSERT INTO links_list (link_name) VALUES ('Saiyan Roar');
INSERT INTO links_list (link_name) VALUES ('Saiyan Warrior Race');
INSERT INTO links_list (link_name) VALUES ('Scientist');
INSERT INTO links_list (link_name) VALUES ('Shadow Dragons');
INSERT INTO links_list (link_name) VALUES ('Shattering the Limit');
INSERT INTO links_list (link_name) VALUES ('Shocking Speed');
INSERT INTO links_list (link_name) VALUES ('Signature Pose');
INSERT INTO links_list (link_name) VALUES ('Solid Support');
INSERT INTO links_list (link_name) VALUES ('Soul vs Soul');
INSERT INTO links_list (link_name) VALUES ('Speedy Retribution');
INSERT INTO links_list (link_name) VALUES ('Strength in Unity');
INSERT INTO links_list (link_name) VALUES ('Strongest Clan in Space');
INSERT INTO links_list (link_name) VALUES ('Super Saiyan');
INSERT INTO links_list (link_name) VALUES ('Super Strike');
INSERT INTO links_list (link_name) VALUES ('Super-God Combat');
INSERT INTO links_list (link_name) VALUES ('Supreme Power');
INSERT INTO links_list (link_name) VALUES ('Supreme Warrior');
INSERT INTO links_list (link_name) VALUES ('Tag Team of Terror');
INSERT INTO links_list (link_name) VALUES ('Team Bardock');
INSERT INTO links_list (link_name) VALUES ('Team Turles');
INSERT INTO links_list (link_name) VALUES ('Telekinesis');
INSERT INTO links_list (link_name) VALUES ('Telepathy');
INSERT INTO links_list (link_name) VALUES ('The First Awakened');
INSERT INTO links_list (link_name) VALUES ('The Ginyu Force');
INSERT INTO links_list (link_name) VALUES ('The Hera Clan');
INSERT INTO links_list (link_name) VALUES ('The Incredible Adventure');
INSERT INTO links_list (link_name) VALUES ('The Innocents');
INSERT INTO links_list (link_name) VALUES ('The Saiyan Lineage');
INSERT INTO links_list (link_name) VALUES ('The Students');
INSERT INTO links_list (link_name) VALUES ('The Wall Standing Tall');
INSERT INTO links_list (link_name) VALUES ('Thirst for Conquest');
INSERT INTO links_list (link_name) VALUES ('Tough as Nails');
INSERT INTO links_list (link_name) VALUES ('Tournament of Power');
INSERT INTO links_list (link_name) VALUES ('Transform');
INSERT INTO links_list (link_name) VALUES ('Turtle School');
INSERT INTO links_list (link_name) VALUES ('Twin Terrors');
INSERT INTO links_list (link_name) VALUES ('Ultimate Lifeform');
INSERT INTO links_list (link_name) VALUES ('Unbreakable Bond');
INSERT INTO links_list (link_name) VALUES ('Universe''s Most Malevolent');
INSERT INTO links_list (link_name) VALUES ('Warrior Gods');
INSERT INTO links_list (link_name) VALUES ('Warriors of Universe 6');
INSERT INTO links_list (link_name) VALUES ('World Tournament Champion');
INSERT INTO links_list (link_name) VALUES ('World Tournament Reborn');
INSERT INTO links_list (link_name) VALUES ('Xenoverse');
INSERT INTO links_list (link_name) VALUES ('Z Fighters');
